language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - cibuilds@duracloud.org
    on_success: change
    on_failure: always
  slack: duraspace:vOBySuKUwM95j2kfbwh0SNxq
install:
  - mvn install -DskipTests -DskipDeploy
script:
  - mvn test -DskipIntTests
sudo: false
addons:
  artifacts: true
    paths:
    - $(git ls-files -o | grep "dura.*\.war$")
  s3_region: us-east-1
