language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - cibuilds@duracloud.org
    on_success: change
    on_failure: always
  slack: duraspace:vOBySuKUwM95j2kfbwh0SNxq
install:
  - mvn install -DskipTests -DskipDeploy
script:
  - mvn test -DskipIntTests
sudo: false
before_deploy:
  - mkdir -p build/webapps
  - cp build/duracloud/duracloud/durastore/*.war build/webapps
  - cp build/duracloud/duracloud/duradmin/*.war build/webapps
deploy:
  - provider: s3
    access_key_id: $ARTIFACTS_KEY
    secret_access_key: $ARTIFACTS_SECRET
    bucket: $ARTIFACTS_BUCKET
    region: $ARTIFACTS_REGION
    skip_cleanup: true
    local_dir: build/webapps
    upload-dir: duracloud/master
    on:
      branch: master
  - provider: s3
    access_key_id: $ARTIFACTS_KEY
    secret_access_key: $ARTIFACTS_SECRET
    bucket: $ARTIFACTS_BUCKET
    region: $ARTIFACTS_REGION
    skip_cleanup: true
    local_dir: build/webapps
    upload-dir: duracloud/develop
    on:
      branch: develop
